import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Banner from "../components/banner";
import Card from "@/components/card";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const onClickBannerButton = () => {
    console.log("click");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoiseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner onClickHandler={onClickBannerButton} buttonText={"Welcome"}>
          Welcome
        </Banner>

        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            width={700}
            height={400}
            alt="hero image"
          />
        </div>

        <div className={styles.cardLayout}>
          <Card
            name={"DarkHouse"}
            imageUrl="/static/hero-image.png"
            href="/coffee-store/dark-house"
            imgAlt="dark-house-shop"
            className={styles.card}
          />
          <Card
            name={"DarkHouse"}
            imageUrl="/static/hero-image.png"
            href="/coffee-store/dark-house"
            imgAlt="dark-house-shop"
            className={styles.card}
          />
          <Card
            name={"DarkHouse"}
            imageUrl="/static/hero-image.png"
            href="/coffee-store/dark-house"
            imgAlt="dark-house-shop"
            className={styles.card}
          />
        </div>
      </main>
    </div>
  );
}
